// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv"
import { join } from "path"
import { defineConfig } from "prisma/config"

// Load environment variables from root directory
const envFile =
  process.env.NODE_ENV === "production" ? ".env.production" : ".env.development"

config({ path: join(__dirname, "../..", envFile) })

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
})
